version: '3.8'

services:
  app:
    image: collinsmutugi/medcard-frontend:v1.0
    container_name: medcard_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"  # Map host port 8080 to container port 80
    environment:
      - VITE_BACKEND_URL=http://localhost:8000  # Set environment variables if needed

  backend:
    image: collinsmutugi/medcard-backend:v1.0
    container_name: medcard_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    env_file:
      - .backend.env  # Load environment variables from .backend.env file

    volumes:
      - backend_data:/app/storage

  db:
    image: collinsmutugi/medcard-db:v1.0
    container_name: medcard_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mutush04
      - MYSQL_DATABASE=medcard
      - MYSQL_PASSWORD=mutush04
    ports:
      - "3306:3306"  # Map host port 3307 to container port 3306
    volumes:
      - db_data:/var/lib/mysql
  fastapi:
    image: collinsmutugi/medcard-facerec:v1.1
    container_name: fastapi-face
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:mutush04@db/medcard
    ports:
      - "8001:8001"

volumes:
  backend_data:
    driver: local
  db_data:
    driver: local
